export const metadata = {
  title: "Resume",
  description: "Generated by create next app",
};
import React from "react";

export default function layout({ children }) {
  return <div>{children}</div>;
}
